# Generated by Django 5.0.3 on 2025-12-16 17:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflow', '0008_tramite_financiamiento_commeta'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('color', models.CharField(default='#6c757d', max_length=7)),
                ('orden', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Estado de pago',
                'verbose_name_plural': 'Estados de pago',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.IntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('monto_pagado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('metodo_pago', models.CharField(blank=True, max_length=50)),
                ('observaciones', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagos_creados', to=settings.AUTH_USER_MODEL)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='pagos.estadopago')),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='workflow.tramite')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['tramite', 'numero_cuota'],
                'unique_together': {('tramite', 'numero_cuota')},
            },
        ),
        migrations.CreateModel(
            name='HistorialPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100)),
                ('detalle', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='pagos.pago')),
            ],
            options={
                'verbose_name': 'Historial de pago',
                'verbose_name_plural': 'Historial de pagos',
                'ordering': ['-fecha'],
            },
        ),
    ]
