# Generated by Django 5.0.3 on 2025-12-17 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_estadospago_iniciales'),
        ('workflow', '0008_tramite_financiamiento_commeta'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaldoAFavor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('utilizado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_utilizacion', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='saldo_generado', to='pagos.pago')),
                ('tramite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='saldos_favor', to='workflow.tramite')),
            ],
            options={
                'verbose_name': 'Saldo a favor',
                'verbose_name_plural': 'Saldos a favor',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
