# Generated by Django 5.0.3 on 2025-12-17 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_saldoafavor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AplicacionSaldo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto_aplicado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones_saldo', to='pagos.pago')),
                ('saldo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to='pagos.saldoafavor')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aplicación de saldo',
                'verbose_name_plural': 'Aplicaciones de saldo',
            },
        ),
    ]
