# Generated by Django 5.0.3 on 2026-01-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0004_aplicacionsaldo'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialpago',
            name='monto_efectivo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto en efectivo de esta transacción'),
        ),
        migrations.AddField(
            model_name='historialpago',
            name='monto_saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Monto de saldo aplicado en esta transacción'),
        ),
    ]
