# Generated by Django 5.0.3 on 2025-06-25 05:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_contrato', models.CharField(max_length=50)),
                ('ubicacion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('domicilio', models.TextField()),
                ('ine', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('tipo', models.CharField(choices=[('propietario', 'Propietario'), ('apoderado', 'Apoderado')], max_length=20)),
                ('instrumento_publico', models.CharField(blank=True, max_length=50, null=True)),
                ('notario_publico', models.CharField(blank=True, max_length=50, null=True)),
                ('nombre_notario', models.CharField(blank=True, max_length=100, null=True)),
                ('proyecto', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='propietario', to='core.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=20)),
                ('norte', models.CharField(max_length=100)),
                ('sur', models.CharField(max_length=100)),
                ('este', models.CharField(max_length=100)),
                ('oeste', models.CharField(max_length=100)),
                ('manzana', models.CharField(blank=True, max_length=20, null=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='core.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=100)),
                ('nacionalidad', models.CharField(max_length=50)),
                ('domicilio', models.TextField()),
                ('ine', models.CharField(max_length=20)),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('tipo', models.CharField(choices=[('vendedor', 'Vendedor'), ('apoderado', 'Apoderado')], max_length=20)),
                ('proyectos', models.ManyToManyField(related_name='vendedores', to='core.proyecto')),
            ],
        ),
    ]
