# Generated by Django 5.0.3 on 2025-06-30 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150, verbose_name='Nombre completo')),
                ('rfc', models.CharField(max_length=13, verbose_name='RFC')),
                ('domicilio', models.TextField(verbose_name='Domicilio')),
                ('telefono', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('ocupacion', models.CharField(blank=True, max_length=100, verbose_name='Ocupación')),
                ('estado_civil', models.CharField(blank=True, max_length=50, verbose_name='Estado civil')),
                ('nacionalidad', models.CharField(blank=True, max_length=50, verbose_name='Nacionalidad')),
                ('originario', models.CharField(blank=True, max_length=100, verbose_name='Lugar de origen')),
                ('tipo_id', models.CharField(max_length=50, verbose_name='Tipo de identificación')),
                ('numero_id', models.CharField(max_length=50, verbose_name='Número de identificación')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
