# Generated by Django 5.0.3 on 2025-07-18 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_propietario_sexo_vendedor_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
