# Generated by Django 5.0.3 on 2025-08-12 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_lote_activo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, null=True, verbose_name='RFC'),
        ),
    ]
