# Generated by Django 5.0.3 on 2025-08-12 16:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_cliente_rfc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propietario',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propietario', to='core.proyecto'),
        ),
    ]
