# Generated by Django 5.0.3 on 2025-08-12 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_propietario_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='autoridad',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_emision_contrato',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_emision_documento',
            field=models.TextField(default=''),
        ),
    ]
