# Generated by Django 5.0.3 on 2025-09-03 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_proyecto_autoridad_proyecto_fecha_emision_contrato_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico'),
        ),
    ]
