# Generated by Django 5.0.3 on 2025-09-18 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_vendedor_fecha_creacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='contraseña_temporal',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
