# Generated by Django 5.0.3 on 2026-02-13 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_beneficiario'),
    ]

    operations = [
        # Operaciones de 0014: Alter fields en Beneficiario
        migrations.AlterField(
            model_name='beneficiario',
            name='numero_id',
            field=models.CharField(blank=True, max_length=50, verbose_name='Número de identificación'),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=1, verbose_name='Sexo'),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, verbose_name='Teléfono'),
        ),
        
        # Operaciones de 0015: Add tipo_proyecto a Proyecto
        migrations.AddField(
            model_name='proyecto',
            name='tipo_proyecto',
            field=models.CharField(choices=[('normal', 'Proyecto Normal'), ('commeta', 'Commeta Community')], default='normal', max_length=20),
        ),
        
        
        # Operaciones de 0015, 0016, 0017: Create ConfiguracionCommeta (modelo completo)
        migrations.CreateModel(
            name='ConfiguracionCommeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zona', models.CharField(choices=[('ambar', 'Ambar'), ('aqua', 'Aqua'), ('magnetita', 'Magnetita'), ('platino', 'Platino')], max_length=50)),
                ('tipo_esquema', models.CharField(choices=[('mensualidades_fijas', 'Mensualidades Fijas'), ('meses_fuertes', 'Meses Fuertes')], default='meses_fuertes', max_length=20)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('apartado_sugerido', models.DecimalField(decimal_places=2, default=3500, max_digits=12)),
                ('enganche_sugerido', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mensualidad_sugerida', models.DecimalField(blank=True, decimal_places=2, help_text='Para esquema de mensualidades fijas', max_digits=12, null=True)),
                ('monto_mensualidad_normal', models.DecimalField(blank=True, decimal_places=2, help_text='Monto de mensualidad normal en esquema de meses fuertes', max_digits=12, null=True)),
                ('monto_mes_fuerte', models.DecimalField(blank=True, decimal_places=2, help_text='Monto de mes fuerte', max_digits=12, null=True)),
                ('monto_pago_final', models.DecimalField(blank=True, decimal_places=2, help_text='Monto del último pago (puede ser diferente al mes fuerte)', max_digits=12, null=True)),
                ('frecuencia_meses_fuertes', models.PositiveIntegerField(blank=True, help_text='Cada cuántos meses se repite un mes fuerte', null=True)),
                ('meses_fuertes_especificos', models.JSONField(blank=True, default=list, help_text='Lista específica de números de meses que son fuertes (ej: [3,8,15,22,29,36])', null=True)),
                ('esquema_personalizado', models.JSONField(blank=True, default=dict, help_text='Estructura completa de pagos para esquemas personalizados futuros')),
                ('activo', models.BooleanField(default=True, help_text='Desactivar configuraciones que ya no se usen')),
                ('total_meses', models.PositiveIntegerField()),
                ('cantidad_meses_fuertes_sugerida', models.PositiveIntegerField(blank=True, help_text='Cantidad sugerida de meses fuertes para esquemas predefinidos', null=True)),
                ('lote', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='configuracion_commeta', to='core.lote')),
            ],
            options={
                'verbose_name': 'Configuración Commeta',
                'verbose_name_plural': 'Configuraciones Commeta',
            },
        ),
    ]

