# Generated by Django 5.0.3 on 2026-02-21 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_proyecto_incluir_cesion_derechos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='superficie_m2',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Si se deja vacío, se calcula automáticamente a partir de las medidas.', max_digits=10, null=True),
        ),
    ]
