# Generated by Django 5.0.3 on 2026-04-15 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_lote_superficie_m2'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiario',
            name='parentesco',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Parentesco'),
        ),
    ]
