# Generated by Django 5.0.3 on 2025-07-04 05:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0004_propietario_sexo_vendedor_sexo'),
        ('financiamiento', '0002_alter_financiamiento_enganche_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tramite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_cliente', models.TextField(blank=True, help_text='Data‑URL base64 de la firma del cliente')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.cliente')),
                ('financiamiento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='financiamiento.financiamiento')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.vendedor')),
            ],
        ),
    ]
