# Generated by Django 5.0.3 on 2025-08-17 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_proyecto_autoridad_proyecto_fecha_emision_contrato_and_more'),
        ('workflow', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='cliente_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tramites_as_second', to='core.cliente'),
        ),
    ]
