# Generated by Django 5.0.3 on 2025-08-22 17:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0002_tramite_cliente_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClausulasEspeciales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clausula_pago', models.TextField(blank=True, verbose_name='Cláusula de Pago Personalizada')),
                ('clausula_deslinde', models.TextField(blank=True, verbose_name='Cláusula de Deslinde Personalizada')),
                ('clausula_promesa', models.TextField(blank=True, verbose_name='Cláusula de Promesa Personalizada')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('tramite', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clausulas_especiales', to='workflow.tramite')),
            ],
            options={
                'verbose_name': 'Cláusulas Especiales del Trámite',
                'verbose_name_plural': 'Cláusulas Especiales de los Trámites',
            },
        ),
    ]
