# Generated by Django 5.0.3 on 2025-09-10 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_cliente_email'),
        ('workflow', '0003_clausulasespeciales'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='persona_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tramite',
            name='persona_tipo',
            field=models.CharField(blank=True, choices=[('vendedor', 'Vendedor'), ('propietario', 'Propietario')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='tramite',
            name='propietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.propietario'),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='vendedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='core.vendedor'),
        ),
    ]
