# Generated by Django 5.0.3 on 2025-09-18 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_tramite_persona_id_tramite_persona_tipo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='usuario_creador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tramites_creados', to=settings.AUTH_USER_MODEL, verbose_name='Usuario que creó el trámite'),
        ),
    ]
