# Generated by Django 5.0.3 on 2025-10-22 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0005_tramite_usuario_creador'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='beneficiario_1_firma',
            field=models.TextField(blank=True, help_text='Firma del beneficiario 1'),
        ),
        migrations.AddField(
            model_name='tramite',
            name='beneficiario_1_nombre',
            field=models.CharField(blank=True, help_text='Nombre del beneficiario 1', max_length=150),
        ),
        migrations.AddField(
            model_name='tramite',
            name='beneficiario_2_firma',
            field=models.TextField(blank=True, help_text='Firma del beneficiario 2'),
        ),
        migrations.AddField(
            model_name='tramite',
            name='beneficiario_2_nombre',
            field=models.CharField(blank=True, help_text='Nombre del beneficiario 2', max_length=150),
        ),
        migrations.AddField(
            model_name='tramite',
            name='firma_cliente2',
            field=models.TextField(blank=True, help_text='Data‑URL base64 de la firma del segundo cliente'),
        ),
        migrations.AddField(
            model_name='tramite',
            name='firma_vendedor',
            field=models.TextField(blank=True, help_text='Data‑URL base64 de la firma del vendedor'),
        ),
        migrations.AddField(
            model_name='tramite',
            name='link_firma_beneficiario1',
            field=models.CharField(blank=True, help_text='Link único para firma de beneficiario', max_length=255),
        ),
        migrations.AddField(
            model_name='tramite',
            name='link_firma_beneficiario2',
            field=models.CharField(blank=True, help_text='Link único para firma del segundo beneficiario', max_length=255),
        ),
        migrations.AddField(
            model_name='tramite',
            name='link_firma_cliente',
            field=models.CharField(blank=True, help_text='Link único para firma del cliente', max_length=255),
        ),
        migrations.AddField(
            model_name='tramite',
            name='link_firma_cliente2',
            field=models.CharField(blank=True, help_text='Link único para firma del segundo cliente', max_length=255),
        ),
        migrations.AddField(
            model_name='tramite',
            name='link_firma_testigo1',
            field=models.CharField(blank=True, help_text='Link único para firma de testigo', max_length=255),
        ),
        migrations.AddField(
            model_name='tramite',
            name='link_firma_testigo2',
            field=models.CharField(blank=True, help_text='Link único para firma del segundo testigo', max_length=255),
        ),
        migrations.AddField(
            model_name='tramite',
            name='testigo_1_firma',
            field=models.TextField(blank=True, help_text='Firma del testigo 1'),
        ),
        migrations.AddField(
            model_name='tramite',
            name='testigo_1_nombre',
            field=models.CharField(blank=True, help_text='Nombre del testigo 1', max_length=150),
        ),
        migrations.AddField(
            model_name='tramite',
            name='testigo_2_firma',
            field=models.TextField(blank=True, help_text='Firma del testigo 2'),
        ),
        migrations.AddField(
            model_name='tramite',
            name='testigo_2_nombre',
            field=models.CharField(blank=True, help_text='Nombre del testigo 2', max_length=150),
        ),
    ]
