# Generated by Django 5.0.3 on 2025-10-24 06:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_beneficiario'),
        ('workflow', '0006_tramite_beneficiario_1_firma_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tramite',
            name='beneficiario_1_nombre',
        ),
        migrations.RemoveField(
            model_name='tramite',
            name='beneficiario_2_nombre',
        ),
        migrations.AddField(
            model_name='tramite',
            name='beneficiario_1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tramites_beneficiario1', to='core.beneficiario', verbose_name='Beneficiario 1'),
        ),
        migrations.AddField(
            model_name='tramite',
            name='beneficiario_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tramites_beneficiario2', to='core.beneficiario', verbose_name='Beneficiario 2'),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='link_firma_beneficiario1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='link_firma_beneficiario2',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
