# Generated by Django 5.0.3 on 2026-02-13 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_proyecto_incluir_cesion_derechos_and_more'),
        ('financiamiento', '0004_financiamientocommeta'),
        ('workflow', '0006_tramite_beneficiario_1_tramite_beneficiario_1_firma_and_more'),
    ]

    operations = [
        # Operación de 0008: Add financiamiento_commeta
        migrations.AddField(
            model_name='tramite',
            name='financiamiento_commeta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tramites_commeta', to='financiamiento.financiamientocommeta', verbose_name='Financiamiento Commeta (si aplica)'),
        ),
        
        # AlterFields indicados por Render
        migrations.AlterField(
            model_name='tramite',
            name='firma_cliente2',
            field=models.TextField(blank=True, help_text='Data-URL base64 de la firma del segundo cliente'),
        ),
        migrations.AlterField(
            model_name='tramite',
            name='firma_vendedor',
            field=models.TextField(blank=True, help_text='Data-URL base64 de la firma del vendedor'),
        ),
    ]

