# Generated by Django 5.0.3 on 2025-12-06 01:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiamiento', '0008_financiamientocommeta_monto_mensualidad_normal_and_more'),
        ('workflow', '0007_remove_tramite_beneficiario_1_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='financiamiento_commeta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tramites_commeta', to='financiamiento.financiamientocommeta', verbose_name='Financiamiento Commeta (si aplica)'),
        ),
    ]
