# Generated by Django 5.0.3 on 2026-02-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0013_tramite_vecino_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='tramite',
            name='link_firma_vendedor',
            field=models.CharField(blank=True, help_text='Link único para firma del vendedor', max_length=255),
        ),
    ]
