# Generated by Django 5.0.3 on 2025-07-02 16:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financiamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(default='', max_length=150, verbose_name='Nombre del cliente')),
                ('tipo_pago', models.CharField(choices=[('contado', 'Contado'), ('financiado', 'Financiado')], max_length=20)),
                ('precio_lote', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Precio del lote')),
                ('apartado', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Apartado')),
                ('fecha_pago_completo', models.DateField(blank=True, null=True, verbose_name='Fecha pago completo')),
                ('monto_pago_completo', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Pago completo')),
                ('enganche', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Enganche')),
                ('fecha_enganche', models.DateField(blank=True, null=True)),
                ('num_mensualidades', models.PositiveIntegerField(verbose_name='N.º de mensualidades')),
                ('monto_mensualidad', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('fecha_primer_pago', models.DateField(blank=True, null=True, verbose_name='Fecha primer pago')),
                ('fecha_ultimo_pago', models.DateField(blank=True, null=True, verbose_name='Fecha último pago')),
                ('monto_pago_final', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='financiamientos', to='core.lote')),
            ],
        ),
    ]
