# Generated by Django 5.0.3 on 2025-07-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiamiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='financiamiento',
            name='enganche',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='financiamiento',
            name='fecha_primer_pago',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financiamiento',
            name='fecha_ultimo_pago',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='financiamiento',
            name='num_mensualidades',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
