# Generated by Django 5.0.3 on 2025-10-17 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiamiento', '0002_alter_financiamiento_enganche_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financiamiento',
            name='activo',
            field=models.BooleanField(default=True, help_text='Desmarcar para desactivar este plan', verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='financiamiento',
            name='es_cotizacion',
            field=models.BooleanField(default=False, help_text='Marcar si es solo una cotización/presupuesto', verbose_name='Es cotización'),
        ),
    ]
