# Generated by Django 5.0.3 on 2025-10-22 06:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_vendedor_contraseña_temporal'),
        ('financiamiento', '0003_financiamiento_activo_financiamiento_es_cotizacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartaIntencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_cliente', models.CharField(max_length=150, verbose_name='Nombre del cliente')),
                ('domicilio', models.TextField(verbose_name='Domicilio')),
                ('tipo_id', models.CharField(default='INE', max_length=10, verbose_name='Tipo de identificación')),
                ('numero_id', models.CharField(max_length=50, verbose_name='Número de identificación')),
                ('telefono_cliente', models.CharField(max_length=20, verbose_name='Teléfono')),
                ('correo_cliente', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('oferta', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Oferta de precio')),
                ('forma_pago', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Transferencia', 'Transferencia')], default='Efectivo', verbose_name='Forma de pago')),
                ('credito_hipotecario', models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], default='No', max_length=10, verbose_name='Crédito hipotecario')),
                ('institucion_financiera', models.CharField(blank=True, help_text='Solo si aplica crédito hipotecario', max_length=100, verbose_name='Institución financiera')),
                ('destinatario_apartado', models.CharField(blank=True, max_length=150, verbose_name='Destinatario del apartado')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('financiamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cartas_intencion', to='financiamiento.financiamiento')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cartas_intencion', to='core.vendedor')),
            ],
        ),
    ]
