# Generated by Django 5.0.3 on 2026-02-13 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_proyecto_incluir_cesion_derechos_and_more'),
        ('financiamiento', '0003_financiamiento_activo_financiamiento_es_cotizacion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinanciamientoCommeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_esquema', models.CharField(choices=[('mensualidades_fijas', 'Mensualidades Fijas'), ('meses_fuertes', 'Meses Fuertes')], default='mensualidades_fijas', max_length=20)),
                ('cantidad_meses_fuertes', models.PositiveIntegerField(blank=True, help_text='Cantidad específica de meses fuertes (puede ser menor al total)', null=True)),
                ('frecuencia_meses_fuertes', models.PositiveIntegerField(blank=True, help_text='Cada cuántos meses se repite un mes fuerte', null=True)),
                ('meses_fuertes_calculados', models.JSONField(default=list, help_text='Lista de números de meses que son fuertes')),
                ('monto_mes_fuerte', models.DecimalField(blank=True, decimal_places=2, help_text='Monto a pagar en los meses fuertes', max_digits=12, null=True)),
                ('monto_mensualidad_normal', models.DecimalField(blank=True, decimal_places=2, help_text='Monto de mensualidad en meses normales (esquema meses fuertes)', max_digits=12, null=True)),
                ('monto_pago_final', models.DecimalField(blank=True, decimal_places=2, help_text='Monto del último pago (puede ser diferente)', max_digits=12, null=True)),
                ('usar_meses_especificos', models.BooleanField(default=False, help_text='Usar lista específica de meses fuertes en lugar de frecuencia')),
                ('configuracion_original', models.ForeignKey(help_text='Configuración base utilizada para este financiamiento', on_delete=django.db.models.deletion.PROTECT, to='core.configuracioncommeta')),
                ('financiamiento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detalle_commeta', to='financiamiento.financiamiento')),
            ],
            options={
                'verbose_name': 'Detalle Financiamiento Commeta',
                'verbose_name_plural': 'Detalles Financiamiento Commeta',
            },
        ),
    ]
