# Generated by Django 5.0.3 on 2026-03-03 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financiamiento', '0008_financiamientocommeta_monto_mensualidad_normal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='financiamientocommeta',
            name='meses_fuertes_personalizados',
            field=models.JSONField(blank=True, default=list, help_text='Lista específica de números de meses que son fuertes (ej: [12, 18, 24, 30, 36])'),
        ),
        migrations.AddField(
            model_name='financiamientocommeta',
            name='montos_fuertes_personalizados',
            field=models.JSONField(blank=True, default=dict, help_text="Diccionario con montos especiales por mes (ej: {'12': 49000, '36': 21000})"),
        ),
    ]
